version: "3.9"

services:
  chat-llama:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: chat-llama
    volumes:
      -  backend_llama-volume:/code/models
    environment:
      - MODEL_NAME=Meta-Llama-3-8B-Instruct.Q5_0.gguf
      - WINDOW_SIZE=10
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]

volumes:
  llama-volume:
    name: backend_llama-volume
    external: true
